//
//  {{classname}}.h
//  MobileMafia
//
//  generated by ccb2cpp by Mobile-Mafia.com
//  
//

#ifndef __MafiaGame__{{classname}}__
#define __MafiaGame__{{classname}}__


#include "cocos2d.h"
#include "cocos-ext.h"

USING_NS_CC;
USING_NS_CC_EXT;
using namespace std;

class {{classname}} :  public {{baseclass}}, public CCBSelectorResolver,public CCBMemberVariableAssigner, public CCNodeLoaderListener
{
public:

    static {{classname}}* create(CCObject* pOwner);

    CCB_STATIC_NEW_AUTORELEASE_OBJECT_WITH_INIT_METHOD({{classname}},create);

    //CCBInterface
   	virtual SEL_MenuHandler onResolveCCBCCMenuItemSelector( cocos2d::CCObject *pTarget, const char *pSelectorName );
   	virtual cocos2d::extension::SEL_CCControlHandler onResolveCCBCCControlSelector( cocos2d::CCObject *pTarget, const char *pSelectorName );
   	virtual bool onAssignCCBMemberVariable( cocos2d::CCObject *pTarget, const char *pMemberVariableName, CCNode *pNode );
   	virtual void onNodeLoaded( cocos2d::CCNode *pNode, cocos2d::extension::CCNodeLoader *pNodeLoader );
    
private:
    {{#menuitem_callbacks}}
    void {{callback}}(CCObject* obj);{{/menuitem_callbacks}}
    
    {{#variables}}
    {{type}}* {{name}} = NULL;{{/variables}}

};

class {{classname}}Loader: public cocos2d::extension::{{baseclass}}Loader {
public:
  CCB_STATIC_NEW_AUTORELEASE_OBJECT_METHOD({{classname}}Loader, loader);
protected:
  CCB_VIRTUAL_NEW_AUTORELEASE_CREATECCNODE_METHOD({{classname}});
};

#endif
