//
//  {{classname}}.cpp
//  MobileMafia
//
//  generated by ccb2cpp by Mobile-Mafia.com
//  
//

#include "{{classname}}.h"


{{classname}}* {{classname}}::create(CCObject* pOwner)
{
    CCNodeLoaderLibrary::sharedCCNodeLoaderLibrary()->registerCCNodeLoader("{{classname}}",{{classname}}Loader::loader());
    CCNodeLoaderLibrary * ccNodeLoaderLibrary = CCNodeLoaderLibrary::sharedCCNodeLoaderLibrary();
    cocos2d::extension::CCBReader * ccbReader = NULL;
    ccNodeLoaderLibrary->registerCCNodeLoader("{{classname}}", {{classname}}Loader::loader());
    ccbReader=new cocos2d::extension::CCBReader(ccNodeLoaderLibrary);
    ccbReader->autorelease();
    return static_cast<{{classname}}*>(ccbReader->readNodeGraphFromFile("{{ccbname}}i", pOwner));

}

SEL_MenuHandler {{classname}}::onResolveCCBCCMenuItemSelector( cocos2d::CCObject *pTarget, const char *pSelectorName )
{
    {{#menuitem_callbacks}}CCB_SELECTORRESOLVER_CCMENUITEM_GLUE(this,"{{callback}}",{{classname}}::{{callback}});
    {{/menuitem_callbacks}}return NULL;
}

cocos2d::extension::SEL_CCControlHandler {{classname}}::onResolveCCBCCControlSelector( cocos2d::CCObject *pTarget, const char *pSelectorName )
{
    return NULL;
}

bool {{classname}}::onAssignCCBMemberVariable( cocos2d::CCObject *pTarget, const char *pMemberVariableName, CCNode *pNode )
{
    {{#variables}}CCB_MEMBERVARIABLEASSIGNER_GLUE(this, "{{name}}", {{type}} *, this->{{name}});
    {{/variables}}return false;
}

void {{classname}}::onNodeLoaded( cocos2d::CCNode *pNode, cocos2d::extension::CCNodeLoader *pNodeLoader ){

}

{{#menuitem_callbacks}}
void {{classname}}::{{callback}}(CCObject* obj)
{
    CCLog("{{classname}}::{{callback}} not implemented");
}
{{/menuitem_callbacks}}